### ISSUE TITLE
Error : Could not check whether there is a proxy configured on system

### ISSUE THREAD

**Issue by Zinkeey** [opentok/opentok-linux-sdk-samples#30] opened 2022-09-06 12:06 UTC
I built and ran the basic video chat application and got the following error. 
![err](https://user-images.githubusercontent.com/112947772/188629446-8a9450d2-ea5f-4975-a55b-9ec5e45122db.png)

After running the application, I opened the vonage api playground and create another client as subscriber and connect to the session. It detects that there is a video and audio to subscribe. But does not show anything on the player.  I am using Ubuntu 20.04.4 LTS.

**Comment by v-kpheng** [comment] 2022-09-28 02:03
@Zinkeey, thanks for filing this issue.

The error being logged is noise.  The connectivity issues you're seeing is likely due to something else.  Lastly, version 2.19 is no longer supported.  Can you please try to reproduce on the most recent version?  Thanks!

Closing, since 2.19 is no longer supported.

**Closed by v-kpheng** 2022-09-28 02:03 UTC
